USE [master]
GO

/****** Object:  Database [AutomaticTasks]    Script Date: 30/08/2021 9:29:01 a. m. ******/
CREATE DATABASE [AutomaticTasks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AutomaticTasks', FILENAME = N'C:\...\AutomaticTasks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AutomaticTasks_log', FILENAME = N'C:\...\AutomaticTasks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutomaticTasks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AutomaticTasks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AutomaticTasks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AutomaticTasks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AutomaticTasks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AutomaticTasks] SET ARITHABORT OFF 
GO

ALTER DATABASE [AutomaticTasks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AutomaticTasks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AutomaticTasks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AutomaticTasks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AutomaticTasks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AutomaticTasks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AutomaticTasks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AutomaticTasks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AutomaticTasks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AutomaticTasks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AutomaticTasks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AutomaticTasks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AutomaticTasks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AutomaticTasks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AutomaticTasks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AutomaticTasks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AutomaticTasks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AutomaticTasks] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [AutomaticTasks] SET  MULTI_USER 
GO

ALTER DATABASE [AutomaticTasks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AutomaticTasks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AutomaticTasks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AutomaticTasks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AutomaticTasks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AutomaticTasks] SET QUERY_STORE = OFF
GO

USE [AutomaticTasks]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [AutomaticTasks] SET  READ_WRITE 
GO


